
server:
  port: 8090


logging:
  file:
    name: dockerlog.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/10weektest?characterEncoding=utf8&serverTimezone=GMT
    password: root
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
